//=================================
//             User
//=================================

//get all users
GET http://localhost:4600/api/users/

###
//get user by ID
GET http://localhost:4600/api/users/5ebc02886d2c1c5f48b97393

###
//post user
POST http://localhost:4600/api/users/ HTTP/1.1
content-type: application/json

{
    "_id": "5ebfc7ca54213a33d4389399",
  "name": "Jaan Raf",
  "email": "jraf@24g.com"
}


//=================================
//             Video
//=================================

###
//get all videos
GET http://localhost:4600/api/videos/

###
//get video by ID
GET http://localhost:4600/api/videos/5ebfd08be4864f3f9c31f67b



//=================================
//             Comment
//=================================
###
//post comment
POST http://localhost:4600/api/comments/ HTTP/1.1
content-type: application/json

{
    "commentTo": "5ebfd08be4864f3f9c31f67b",
    "content": "I loved this video"
}

###
//get comment by videoID
GET http://localhost:4600/api/comments/5ebbca32a2891f5a0c194f9e


//=================================
//             Sentiments 
//=================================

###
//Like a video
POST http://localhost:4600/api/sentiments/savelike HTTP/1.1
content-type: application/json

{
    "userId": "5ebc0344f965b920c822e59b",
    "videoId": "5ebfd08be4864f3f9c31f67b"
}

###
//get likes by videoID
GET http://localhost:4600/api/sentiments/getlikes/5ebfd08be4864f3f9c31f67b


###
//Dislike a video
POST http://localhost:4600/api/sentiments/savedisike HTTP/1.1
content-type: application/json

{
    "userId": "5ebc0344f965b920c822e59b",
    "videoId": "5ebfd08be4864f3f9c31f67b"
}

###
//get dislikes by videoID
GET http://localhost:4600/api/sentiments/getdislikes/5ebfd08be4864f3f9c31f67b




//==================================================
//             Sentiments Suggested Feature
//  Unlike a liked video and undislike a disliked video
//==================================================

###
//unlike a video
DELETE  http://localhost:4600/api/sentiments/unlike/5ebc0344f965b920c822e59b/5ebfd08be4864f3f9c31f67b


###
//undislike a video
DELETE  http://localhost:4600/api/sentiments/undislike/5ebc0344f965b920c822e59b/5ebfd08be4864f3f9c31f67b